### ISSUE TITLE
AMS AES Encryption fail with SpriteTip

### ISSUE THREAD

**Issue by sandeshmanoharV2** [RickShahid/SpriteTip#1]
We had used below url to Generate a thumbnail sprite
https://docs.microsoft.com/en-us/azure/media-services/previous/generate-thumbnail-sprite

Using Media Encoder Standard we had generated a thumbnail sprite single (large) image, together with a VTT file and we want azure media player should show the thumbnail image of the respective time frame on hover of the timeline so for that we got plugin from Azure website sprite-tip below url-
https://github.com/RickShahid/SpriteTip

We gets error 403 forbidden only for the plugin when plugin call XMLHttpRequest GetThumbnailTrack from VTT file url which is AES Encrypted 

Azure Media player plays video fine for both with and without AES JWT Token, Main thing is when sprite-tip plugin call XMLHttpRequest to GetThumbnailTrack from VTT file url which is AES Encrypted that time is gives 403 forbidden error and doesn't show thumbnail image on hover of timeline

For No encryption its works properly and shows thumbnail image on hover of timeline

**Comment by sandeshmanoharV2** [comment]
Our main Question is How we can authenticate sprite-Tip plugin using AES Encrypted jwt token based authenticate asset which is having vtt file with image and video

**Comment by RickShahid** [comment]
**Dynamic** AES 128 encryption does work with Sprite Tip since it does not apply to the .vtt text file.
https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-protect-with-aes128

If you are referring to **static** storage AES encryption that was built into AMS v2, that feature has been deprecated in favor of native Azure storage encryption at rest, which was added after AMS v2 released.
https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-rest-storage-encryption

If you are still having an issue, please let me know.

Thanks.

Rick
